name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Render deploy
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
